name: Generar Snake Game desde la cuadrícula de contribución

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Generar Snake
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: alusilcof5
          outputs: |
            github-contribution-grid-snake.svg?palette=github-dark&color_snake=azul

      - name: Publicar en el branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

