name: Generar Snake Game desde la cuadrícula de contribución

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta diariamente a la medianoche
  workflow_dispatch:     # Permite ejecución manual del workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generar Snake
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: alusilcof5
          outputs: |
            snake-dark.svg?palette=github-dark&color_snake=azul
            snake-light.svg?palette=github-light&color_snake=verde
            snake-ocean.gif?color_snake=naranja&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Subir artefactos al repositorio
        uses: actions/upload-artifact@v4
        with:
          name: snake-art
          path: dist
